all: list_single.png list_double.png \
	list_non_intrusive.png list_non_intrusive_gen.png \
	list_intrusive.png list_intrusive_gen.png

list_single.png: list_single.dia
	dia -s 400 -t png list_single.dia

list_double.png: list_double.dia
	dia -s 450 -t png list_double.dia

list_non_intrusive.png: list_non_intrusive.dia
	dia -s 500 -t png list_non_intrusive.dia

list_non_intrusive_gen.png: list_non_intrusive_gen.dia
	dia -s 600 -t png list_non_intrusive_gen.dia

list_intrusive.png: list_intrusive.dia
	dia -s 600 -t png list_intrusive.dia

list_intrusive_gen.png: list_intrusive_gen.dia
	dia -s 600 -t png list_intrusive_gen.dia
